feat: scaffold multiple channels
teknologi-umum/gitgram pull request #18
Opened 2022-04-23 14:50 UTC by aldy505

partially closes #13

2022-04-23 15:04 UTC, elianiva requested changes

2022-04-23 15:04 UTC, elianiva commented on src/index.ts
> +  const repositoryUrl = ctx.message.text.slice(7);
kasih comment angka 7 ini apa (panjangnya `/start ` kan), biar ngga jadi magic number

atau kalo sok ganteng jadiin `const [_, repositoryUrl] = ctx.message.text.split(" ")`

2022-04-23 15:04 UTC, elianiva commented on src/server/github.ts
> +      }
ini body parser nanti bakal diextract buat dipake yg lain juga ngga?

2022-04-23 15:11 UTC, aldy505 commented on src/index.ts
> +import { Telegraf } from "telegraf";
beda PR

2022-04-23 15:11 UTC, aldy505 commented on src/server/github.ts
> +      }
iya. beda PR.  ini buat scaffold.

2022-04-23 15:12 UTC, elianiva commented on src/index.ts
> +import { Telegraf } from "telegraf";
ok

2022-06-24 00:24 UTC, elianiva commented
masih mau lanjutin ini?

2022-06-24 08:50 UTC, elianiva commented
kalo gamau lanjutin biar aku yg lanjutin

2022-06-24 15:39 UTC, aldy505 commented
ide yang bagus, gas

2022-06-28 04:24 UTC, aldy505 commented
seems like you have too much free time lol

2022-06-28 04:36 UTC, aldy505 commented on src/index.ts
> +const config = parseGura(configFile) as AppConfig;
should also validate is there is any invalid configuration being set on the gura conf file

2022-06-28 04:37 UTC, aldy505 commented on src/index.ts
> +    }
should not parse anything if the `body` length is 0

2022-06-28 04:38 UTC, aldy505 commented on src/infrastructure/ConsoleLogger.ts
> +    // eslint-disable-next-line no-console
import console instead of disabling eslint like this

2022-07-19 11:57 UTC, merged